# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200729_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10, verbose_name='名称'),
        ),
    ]
